# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mean_shift_params.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(520, 463)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bandwidth_text = QtWidgets.QLabel(self.groupBox)
        self.bandwidth_text.setObjectName("bandwidth_text")
        self.horizontalLayout.addWidget(self.bandwidth_text)
        self.bandwidth = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bandwidth.sizePolicy().hasHeightForWidth())
        self.bandwidth.setSizePolicy(sizePolicy)
        self.bandwidth.setClearButtonEnabled(False)
        self.bandwidth.setObjectName("bandwidth")
        self.horizontalLayout.addWidget(self.bandwidth)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.max_iter_text = QtWidgets.QLabel(self.groupBox_3)
        self.max_iter_text.setObjectName("max_iter_text")
        self.horizontalLayout_3.addWidget(self.max_iter_text)
        self.max_iter = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_iter.sizePolicy().hasHeightForWidth())
        self.max_iter.setSizePolicy(sizePolicy)
        self.max_iter.setObjectName("max_iter")
        self.horizontalLayout_3.addWidget(self.max_iter)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cluster_all_text = QtWidgets.QLabel(self.groupBox_4)
        self.cluster_all_text.setObjectName("cluster_all_text")
        self.horizontalLayout_4.addWidget(self.cluster_all_text)
        self.cluster_all = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cluster_all.sizePolicy().hasHeightForWidth())
        self.cluster_all.setSizePolicy(sizePolicy)
        self.cluster_all.setObjectName("cluster_all")
        self.cluster_all.addItem("")
        self.cluster_all.addItem("")
        self.horizontalLayout_4.addWidget(self.cluster_all)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.OKButton = QtWidgets.QPushButton(self.groupBox_5)
        self.OKButton.setObjectName("OKButton")
        self.horizontalLayout_5.addWidget(self.OKButton)
        self.CancelButton = QtWidgets.QPushButton(self.groupBox_5)
        self.CancelButton.setObjectName("CancelButton")
        self.horizontalLayout_5.addWidget(self.CancelButton)
        self.verticalLayout.addWidget(self.groupBox_5)

        self.retranslateUi(Form)
        self.CancelButton.clicked['bool'].connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Mean Shift Parameters"))
        self.bandwidth_text.setText(_translate("Form", "bandwidth: float , default = None"))
        self.bandwidth.setText(_translate("Form", "None"))
        self.max_iter_text.setText(_translate("Form", "max_iter: int , default = 300"))
        self.max_iter.setText(_translate("Form", "300"))
        self.cluster_all_text.setText(_translate("Form", "cluster_all: bool , default = True"))
        self.cluster_all.setItemText(0, _translate("Form", "True"))
        self.cluster_all.setItemText(1, _translate("Form", "False"))
        self.OKButton.setText(_translate("Form", "OK"))
        self.CancelButton.setText(_translate("Form", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
