from PyQt5 import QtCore, QtGui, QtWidgets

## UI for asking Affinity Propagation Clustering Parameters
#  Generated from PyQT5 Designer
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(520, 463)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.damping_text = QtWidgets.QLabel(self.groupBox)
        self.damping_text.setObjectName("damping_text")
        self.horizontalLayout.addWidget(self.damping_text)
        self.damping = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.damping.sizePolicy().hasHeightForWidth())
        self.damping.setSizePolicy(sizePolicy)
        self.damping.setClearButtonEnabled(False)
        self.damping.setObjectName("damping")
        self.horizontalLayout.addWidget(self.damping)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.max_iter_text = QtWidgets.QLabel(self.groupBox_3)
        self.max_iter_text.setObjectName("max_iter_text")
        self.horizontalLayout_3.addWidget(self.max_iter_text)
        self.max_iter = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_iter.sizePolicy().hasHeightForWidth())
        self.max_iter.setSizePolicy(sizePolicy)
        self.max_iter.setObjectName("max_iter")
        self.horizontalLayout_3.addWidget(self.max_iter)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_6 = QtWidgets.QGroupBox(Form)
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.convergence_iter_text = QtWidgets.QLabel(self.groupBox_6)
        self.convergence_iter_text.setObjectName("convergence_iter_text")
        self.horizontalLayout_6.addWidget(self.convergence_iter_text)
        self.convergence_iter = QtWidgets.QLineEdit(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.convergence_iter.sizePolicy().hasHeightForWidth())
        self.convergence_iter.setSizePolicy(sizePolicy)
        self.convergence_iter.setObjectName("convergence_iter")
        self.horizontalLayout_6.addWidget(self.convergence_iter)
        self.verticalLayout.addWidget(self.groupBox_6)
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.affinity_text = QtWidgets.QLabel(self.groupBox_4)
        self.affinity_text.setObjectName("affinity_text")
        self.horizontalLayout_4.addWidget(self.affinity_text)
        self.affinity = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.affinity.sizePolicy().hasHeightForWidth())
        self.affinity.setSizePolicy(sizePolicy)
        self.affinity.setObjectName("affinity")
        self.affinity.addItem("")
        self.affinity.addItem("")
        self.horizontalLayout_4.addWidget(self.affinity)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_7 = QtWidgets.QGroupBox(Form)
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.random_state_text = QtWidgets.QLabel(self.groupBox_7)
        self.random_state_text.setObjectName("random_state_text")
        self.horizontalLayout_7.addWidget(self.random_state_text)
        self.random_state = QtWidgets.QLineEdit(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.random_state.sizePolicy().hasHeightForWidth())
        self.random_state.setSizePolicy(sizePolicy)
        self.random_state.setObjectName("random_state")
        self.horizontalLayout_7.addWidget(self.random_state)
        self.verticalLayout.addWidget(self.groupBox_7)
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.OKButton = QtWidgets.QPushButton(self.groupBox_5)
        self.OKButton.setObjectName("OKButton")
        self.horizontalLayout_5.addWidget(self.OKButton)
        self.CancelButton = QtWidgets.QPushButton(self.groupBox_5)
        self.CancelButton.setObjectName("CancelButton")
        self.horizontalLayout_5.addWidget(self.CancelButton)
        self.verticalLayout.addWidget(self.groupBox_5)

        self.retranslateUi(Form)
        self.CancelButton.clicked['bool'].connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Affinity Propagation Parameters"))
        self.damping_text.setText(_translate("Form", "damping: float , default = 0.5"))
        self.damping.setText(_translate("Form", "0.5"))
        self.max_iter_text.setText(_translate("Form", "max_iter: int , default = 200"))
        self.max_iter.setText(_translate("Form", "200"))
        self.convergence_iter_text.setText(_translate("Form", "convergence_iter: int , default = 15"))
        self.convergence_iter.setText(_translate("Form", "15"))
        self.affinity_text.setText(_translate("Form", "affinity: str , default = euclidean"))
        self.affinity.setItemText(0, _translate("Form", "euclidean"))
        self.affinity.setItemText(1, _translate("Form", "precomputed"))
        self.random_state_text.setText(_translate("Form", "random_state: int , default = None"))
        self.random_state.setText(_translate("Form", "None"))
        self.OKButton.setText(_translate("Form", "OK"))
        self.CancelButton.setText(_translate("Form", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
