# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hierarchical_params.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(520, 463)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.n_clusters_text = QtWidgets.QLabel(self.groupBox)
        self.n_clusters_text.setObjectName("n_clusters_text")
        self.horizontalLayout.addWidget(self.n_clusters_text)
        self.n_clusters = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.n_clusters.sizePolicy().hasHeightForWidth())
        self.n_clusters.setSizePolicy(sizePolicy)
        self.n_clusters.setClearButtonEnabled(False)
        self.n_clusters.setObjectName("n_clusters")
        self.horizontalLayout.addWidget(self.n_clusters)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.affinity_text = QtWidgets.QLabel(self.groupBox_3)
        self.affinity_text.setObjectName("affinity_text")
        self.horizontalLayout_3.addWidget(self.affinity_text)
        self.affinity = QtWidgets.QComboBox(self.groupBox_3)
        self.affinity.setObjectName("affinity")
        self.affinity.addItem("")
        self.affinity.addItem("")
        self.affinity.addItem("")
        self.affinity.addItem("")
        self.affinity.addItem("")
        self.affinity.addItem("")
        self.horizontalLayout_3.addWidget(self.affinity)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_6 = QtWidgets.QGroupBox(Form)
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.linkage_text = QtWidgets.QLabel(self.groupBox_6)
        self.linkage_text.setObjectName("linkage_text")
        self.horizontalLayout_6.addWidget(self.linkage_text)
        self.linkage = QtWidgets.QComboBox(self.groupBox_6)
        self.linkage.setObjectName("linkage")
        self.linkage.addItem("")
        self.linkage.addItem("")
        self.linkage.addItem("")
        self.linkage.addItem("")
        self.horizontalLayout_6.addWidget(self.linkage)
        self.verticalLayout.addWidget(self.groupBox_6)
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.OKButton = QtWidgets.QPushButton(self.groupBox_5)
        self.OKButton.setObjectName("OKButton")
        self.horizontalLayout_5.addWidget(self.OKButton)
        self.CancelButton = QtWidgets.QPushButton(self.groupBox_5)
        self.CancelButton.setObjectName("CancelButton")
        self.horizontalLayout_5.addWidget(self.CancelButton)
        self.verticalLayout.addWidget(self.groupBox_5)

        self.retranslateUi(Form)
        self.CancelButton.clicked['bool'].connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Hierarchical Clustering Parameters"))
        self.n_clusters_text.setText(_translate("Form", "n_clusters: int , default = 2"))
        self.n_clusters.setText(_translate("Form", "2"))
        self.affinity_text.setText(_translate("Form", "affinity: str , default = euclidean"))
        self.affinity.setItemText(0, _translate("Form", "euclidean"))
        self.affinity.setItemText(1, _translate("Form", "l1"))
        self.affinity.setItemText(2, _translate("Form", "l2"))
        self.affinity.setItemText(3, _translate("Form", "manhattan"))
        self.affinity.setItemText(4, _translate("Form", "cosine"))
        self.affinity.setItemText(5, _translate("Form", "precomputed"))
        self.linkage_text.setText(_translate("Form", "linkage: str , default = ward"))
        self.linkage.setItemText(0, _translate("Form", "ward"))
        self.linkage.setItemText(1, _translate("Form", "complete"))
        self.linkage.setItemText(2, _translate("Form", "average"))
        self.linkage.setItemText(3, _translate("Form", "single"))
        self.OKButton.setText(_translate("Form", "OK"))
        self.CancelButton.setText(_translate("Form", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
