from PyQt5 import QtCore, QtGui, QtWidgets

## UI for asking Spectral Clustering Parameters
#  Generated from PyQT5 Designer
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(520, 463)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.n_clusters_text = QtWidgets.QLabel(self.groupBox)
        self.n_clusters_text.setObjectName("n_clusters_text")
        self.horizontalLayout.addWidget(self.n_clusters_text)
        self.n_clusters = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.n_clusters.sizePolicy().hasHeightForWidth())
        self.n_clusters.setSizePolicy(sizePolicy)
        self.n_clusters.setClearButtonEnabled(False)
        self.n_clusters.setObjectName("n_clusters")
        self.horizontalLayout.addWidget(self.n_clusters)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.n_components_text = QtWidgets.QLabel(self.groupBox_3)
        self.n_components_text.setObjectName("n_components_text")
        self.horizontalLayout_3.addWidget(self.n_components_text)
        self.n_components = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.n_components.sizePolicy().hasHeightForWidth())
        self.n_components.setSizePolicy(sizePolicy)
        self.n_components.setObjectName("n_components")
        self.horizontalLayout_3.addWidget(self.n_components)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_6 = QtWidgets.QGroupBox(Form)
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.n_init_text = QtWidgets.QLabel(self.groupBox_6)
        self.n_init_text.setObjectName("n_init_text")
        self.horizontalLayout_6.addWidget(self.n_init_text)
        self.n_init = QtWidgets.QLineEdit(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.n_init.sizePolicy().hasHeightForWidth())
        self.n_init.setSizePolicy(sizePolicy)
        self.n_init.setObjectName("n_init")
        self.horizontalLayout_6.addWidget(self.n_init)
        self.verticalLayout.addWidget(self.groupBox_6)
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.assign_labels_text = QtWidgets.QLabel(self.groupBox_4)
        self.assign_labels_text.setObjectName("assign_labels_text")
        self.horizontalLayout_4.addWidget(self.assign_labels_text)
        self.assign_labels = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.assign_labels.sizePolicy().hasHeightForWidth())
        self.assign_labels.setSizePolicy(sizePolicy)
        self.assign_labels.setObjectName("assign_labels")
        self.assign_labels.addItem("")
        self.assign_labels.addItem("")
        self.assign_labels.addItem("")
        self.horizontalLayout_4.addWidget(self.assign_labels)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.OKButton = QtWidgets.QPushButton(self.groupBox_5)
        self.OKButton.setObjectName("OKButton")
        self.horizontalLayout_5.addWidget(self.OKButton)
        self.CancelButton = QtWidgets.QPushButton(self.groupBox_5)
        self.CancelButton.setObjectName("CancelButton")
        self.horizontalLayout_5.addWidget(self.CancelButton)
        self.verticalLayout.addWidget(self.groupBox_5)

        self.retranslateUi(Form)
        self.CancelButton.clicked['bool'].connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Spectral Clustering Parameters"))
        self.n_clusters_text.setText(_translate("Form", "n_clusters: int , default = 3"))
        self.n_clusters.setText(_translate("Form", "3"))
        self.n_components_text.setText(_translate("Form", "n_components: int , default = None"))
        self.n_components.setText(_translate("Form", "None"))
        self.n_init_text.setText(_translate("Form", "n_init: int , default = 10"))
        self.n_init.setText(_translate("Form", "10"))
        self.assign_labels_text.setText(_translate("Form", "assign_labels: str , default = kmeans"))
        self.assign_labels.setItemText(0, _translate("Form", "kmeans"))
        self.assign_labels.setItemText(1, _translate("Form", "discretize"))
        self.assign_labels.setItemText(2, _translate("Form", "cluster_qr"))
        self.OKButton.setText(_translate("Form", "OK"))
        self.CancelButton.setText(_translate("Form", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
